[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
anchor_student_intro = "92uUahvJkKWsZSfhqnoDH7CGjCpmSs3sN8FypfJdhJjy"

[programs.devnet]
anchor_student_intro = "92uUahvJkKWsZSfhqnoDH7CGjCpmSs3sN8FypfJdhJjy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
